listeners:
  client:
    protocol: SASL_PLAINTEXT
  controller:
    protocol: SASL_PLAINTEXT
  interbroker:
    protocol: SASL_PLAINTEXT
  external:
    protocol: SASL_PLAINTEXT

controller:
  replicaCount: 0
  
broker:
  configOverrides:
        server:
          properties:
            message.max.bytes: 2024000   
            replica.fetch.max.bytes: 2024000 
  replicaCount: 3 
  persistence:
    size: 20Gi
  resources:
    limits:
      memory: "4Gi"
      cpu: "2"
    requests:
      memory: "2Gi"
      cpu: "1"

serviceAccount:
  create: false

provisioning:
  enabled: true
  numPartitions: 3
  replicationFactor: 3
  topics:
    - name: cve

kraft:
  enabled: false

zookeeper:
  enabled: true
  persistence:
    size: 2Gi

extraEnvVars:
  - name: KAFKA_ENABLE_KRAFT
    value: "false"
