apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: clustering-ninja-crt-prod
  namespace: istio-ingress
spec:
  secretName: clustering-ninja-crt
  issuerRef:
    name: prod-cluster-issuer
    kind: ClusterIssuer
    group: cert-manager.io
  dnsNames:
  - "*.dev.clustering.ninja"
