name: webapp
namespace: chatbot-ns

replicas: 3
restartPolicy: Always

ollama:
  service:
    url: http://ollama.ollama.svc.cluster.local
  model: phi3

quitquitquit:
  url: http://127.0.0.1:15020/quitquitquit

apiContainer:
  name: cve-rag-api
  image: dongrep/cve-rag-api
  tag: latest
  imagePullPolicy: Always

uiContainer:
  name: chatbot-ui
  image: dongrep/cve-rag-ui
  tag: latest
  imagePullPolicy: Always
  api_url: http://chatbot-api-service.chatbot-ns.svc.cluster.local/recommend

imagePullSecrets:
  type: kubernetes.io/dockerconfigjson
  
db_secrets:
  type: Opaque

configMap:
  host: webapp-postgresql.psql-ns.svc.cluster.local
  db_port: 5432
  db: cve
  ollama_host: ollama.ollama.svc.cluster.local
  ollama_model: phi3
  flyway:
    url: jdbc:postgresql://webapp-postgresql.psql-ns.svc.cluster.local:5432/cve
    user: piyush
    schema: cve

resources:
  requests:
    cpu: "100m"
    memory: "200Mi"
  limits:
    cpu: "200m"
    memory: "400Mi"

autoscaling:
  minReplicas: "2"
  maxReplicas: "4"
  targetCPUUtilizationPercentage: "80"

pdb:
  minAvailable: "2"

rbac:
  automountServiceAccountToken: false

tlsSecretName: clustering-ninja-crt

gateway:
  name: chatbot-gateway

vsHost: chatbot-ui-service.chatbot-ns.svc.cluster.local
vsPort: 80
