apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  components:
    base:
      enabled: true
    egressGateways:
    - enabled: false
      name: istio-egressgateway
    ingressGateways:
    - enabled: true
      name: istio-ingressgateway
    pilot:
      enabled: true
  hub: docker.io/istio
  profile: custom
  tag: 1.22.3
  values:
    imagePullPolicy: IfNotPresent
    pilot:
      traceSampling: 100
    defaultRevision: ""
    gateways:
      istio-egressgateway: {}
      istio-ingressgateway: {}
    global:
      configValidation: true
      istioNamespace: istio-system
    meshConfig:
      accessLogFile: /dev/stdout
      outboundTrafficPolicy:
        mode: ALLOW_ANY # Allow any outbound traffic by default

defaults:
  global:
    logAsJson: true
