apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: grafana-gateway
  namespace: monitoring
spec:
  selector:
    istio: gateway # Use Istio’s default ingress gateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "grafana.dev.clustering.ninja" # Replace with your domain
    - port:
        number: 443
        name: https
        protocol: HTTPS
      hosts:
        - "grafana.dev.clustering.ninja" # Replace with your domain
      tls:
        mode: SIMPLE
        credentialName: {{ .Values.tlsSecretName }} 
