listeners:
  client:
    protocol: PLAINTEXT
  controller:
    protocol: PLAINTEXT
  interbroker:
    protocol: PLAINTEXT
  external:
    protocol: PLAINTEXT

controller:
  replicaCount: 0
  resourcesPreset: "small"

broker:
  configOverrides:
    server:
      properties:
        message.max.bytes: 2024000
        replica.fetch.max.bytes: 2024000
  replicaCount: 3
  persistence:
    size: 20Gi
    storageClass: "gp2"
  resourcesPreset: "medium"
  autoscaling:
    hpa:
      enabled: true
      targetCPU: "90"
      minReplicas: "3"
      maxReplicas: "4"
  pdb:
    create: true
    minAvailable: "3"

serviceAccount:
  create: false

provisioning:
  enabled: true
  topics:
    - name: cve
      partitions: 12 
      replicationFactor: 3
  extraProvisioningCommands: 
    - curl -fsI -X POST http://localhost:15020/quitquitquit

kraft:
  enabled: false

zookeeper:
  enabled: true
  persistence:
    storageClass: "gp2"
    size: 2Gi

extraEnvVars:
  - name: KAFKA_ENABLE_KRAFT
    value: "false"

log4j:
  appenders: |
    log4j.appender.CONSOLE=org.apache.log4j.ConsoleAppender
    log4j.appender.CONSOLE.layout=org.apache.log4j.json.JSONEventLayoutV1
  rootLogger: "INFO, CONSOLE"
