listeners:
  client:
    protocol: PLAINTEXT
  controller:
    protocol: PLAINTEXT
  interbroker:
    protocol: PLAINTEXT
  external:
    protocol: PLAINTEXT

controller:
  replicaCount: 0

broker:
  configOverrides:
    server:
      properties:
        message.max.bytes: 2024000
        replica.fetch.max.bytes: 2024000
  replicaCount: 3
  persistence:
    size: 20Gi
    storageClass: "gp2"
  resources:
    limits:
      memory: "2Gi"
      cpu: "1.5"
    requests:
      memory: "1Gi"
      cpu: "0.5"

serviceAccount:
  create: false

provisioning:
  enabled: true
  numPartitions: 3
  replicationFactor: 3
  topics:
    - name: cve

kraft:
  enabled: false

zookeeper:
  enabled: true
  persistence:
    storageClass: "gp2"
    size: 2Gi

extraEnvVars:
  - name: KAFKA_ENABLE_KRAFT
    value: "false"

metrics:
  jmx:
    enabled: true
  serviceMonitor:
    enabled: true
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s
    labels:
      release: prometheus

  resources:
    limits:
      memory: "128Mi"
      cpu: "100m"
    requests:
      memory: "256Mi"
      cpu: "200m"
