enabled: true
image:
  tag: 15.5.0-debian-11-r5
auth:
  enablePostgresUser: true
  database: cve
primary:
  persistence:
    storageClass: "gp2"
    size: 10Gi
  labels:
    app: webapp-db
  podLabels:
    app: webapp-db
  resources:
    limits:
      memory: "768Mi"
      cpu: "0.5"
    requests:
      memory: "128Mi"
      cpu: "0.3"
  networkPolicy:
    enabled: false

metrics:
  enabled: true
  serviceMonitor:
    enabled: true
    interval: 30s
    labels:
      release: prometheus

  service:
    ports:
      metrics: 9187
    clusterIP: ""
    sessionAffinity: None
    annotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "9187" # This should match the metrics port of PostgreSQL

  prometheusRule:
    enabled: true
    labels:
      release: prometheus # Add any additional labels required by your Prometheus setup
    rules:
      - alert: HugeReplicationLag
        expr: pg_replication_lag{service="{{ printf "%s-metrics" (include "common.names.fullname" .) }}"} / 3600 > 1
        for: 1m
        labels:
          severity: critical
        annotations:
          description: replication for {{ include "common.names.fullname" . }} PostgreSQL is lagging by {{ "{{ $value }}" }} hour(s).
          summary: PostgreSQL replication is lagging by {{ "{{ $value }}" }} hour(s).

  resources:
    limits:
      memory: "256Mi"
      cpu: "200m"
    requests:
      memory: "128Mi"
      cpu: "100m"
