apiVersion: apps/v1
kind: Deployment
metadata:
  app.kubernetes.io/managed-by: Helm
  meta.helm.sh/release-name: {{ .Release.Name }}
  name: {{ .Values.name }} 
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      name: {{ .Values.name }}
  template:
    metadata:
      labels:
        name: {{ .Values.name }}
    spec:
      containers:
      - name: {{ .Values.name }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        ports:
        - name: http
          containerPort: 11434
          protocol: TCP
        resources:
          requests:
            memory: {{ .Values.resources.requests.memory }}
            cpu: {{ .Values.resources.requests.cpu }}
          limits:
            memory: {{ .Values.resources.limits.memory }}
            cpu: {{ .Values.resources.limits.cpu }}
