name: webapp
namespace: cve-consumer

replicas: 3
restartPolicy: Always

container:
  name: webapp-cve-consumer
  image: dongrep/webapp_cve_consumer
  tag: latest
  imagePullPolicy: Always

initcontainer:
  name: db-migrate
  image: dongrep/webapp_db_migrate
  tag: latest
  imagePullPolicy: Always

imagePullSecrets:
  type: kubernetes.io/dockerconfigjson

db_secrets:
  type: Opaque

configMap:
  host: webapp-postgresql.cve-consumer.svc.cluster.local
  db_port: 5432
  db: cve
  brokers: webapp-kafka.kafka-ns.svc.cluster.local:9092
  topic: cve
  group_id: cve-consumer
  flyway:
    url: jdbc:postgresql://webapp-postgresql.cve-consumer.svc.cluster.local:5432/cve
    user: piyush
    schema: cve
